eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka"

spring:
  application:
    name: item-service
  data:
    jdbc:
      repositories:
        enabled: true

  datasource:
    hikari:
      maximum-pool-size: 5
    password: 1234
    username: root
    url: "jdbc:mysql://localhost:3306/micro-services-homework-item?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create



server:
  port: 8082

