spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    embedded-database-connection: hsqldb
    generate-unique-name: true
    url: "jdbc:mysql://localhost:3306/micro-services-homework-user?createDatabaseIfNotExist=true"
    username: "root"
    password: "1234"
    hikari:
      maximum-pool-size: 5

  application:
    name: "user-service"

  data:
    jdbc:
      repositories:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url :
      defaultZone : "http://localhost:8761/eureka/"
server:
  port: 8081


